name: build nodejs prem
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - nodejs-prem/**
permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: relixofficial/devbotkit
  
jobs:
  push:
    name: "devbotkit:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - lts-vip
          - latest-vip
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
            ${{ github.repository_owner == 'pelican-eggs' && format('ghcr.io/${{ env.IMAGE_NAME }}:{0}', matrix.tag) || '' }}